import fs from "fs";
import path from "path";

// Candidates list for each level (to reach exactly 300 words per level)
// We provide ~105-110 curated candidates per level to ensure we get exactly 100 new unique words after filtering existing ones.
const candidates = {
  1: [
    ["手", "手", "shǒu", "Thủ", "Tay, bàn tay", "Con người / People"],
    ["头", "頭", "tóu", "Đầu", "Đầu (bộ phận cơ thể)", "Con người / People"],
    ["心", "心", "xīn", "Tâm", "Tim, lòng, tâm trí", "Con người / People"],
    ["眼", "眼", "yǎn", "Nhãn", "Mắt", "Con người / People"],
    ["耳", "耳", "ěr", "Nhĩ", "Tai", "Con người / People"],
    ["鼻", "鼻", "bí", "Tị", "Mũi", "Con người / People"],
    ["牙", "牙", "yá", "Nha", "Răng", "Con người / People"],
    ["足", "足", "zú", "Túc", "Chân, bàn chân", "Con người / People"],
    ["身", "身", "shēn", "Thân", "Thân thể, mình", "Con người / People"],
    ["男", "男", "nán", "Nam", "Nam giới, đàn ông", "Con người / People"],
    ["哥", "哥", "gē", "Ca", "Anh trai", "Con người / People"],
    ["姐", "姐", "jiě", "Tỷ", "Chị gái", "Con người / People"],
    ["弟", "弟", "dì", "Đệ", "Em trai", "Con người / People"],
    ["妹", "妹", "mèi", "Muội", "Em gái", "Con người / People"],
    ["牛", "牛", "niú", "Ngưu", "Con bò", "Động vật / Animals"],
    ["羊", "羊", "yáng", "Dương", "Con dê", "Động vật / Animals"],
    ["马", "馬", "mǎ", "Mã", "Con ngựa", "Động vật / Animals"],
    ["鸟", "鳥", "niǎo", "Điểu", "Con chim", "Động vật / Animals"],
    ["鱼", "魚", "yú", "Ngư", "Con cá", "Động vật / Animals"],
    ["鸡", "雞", "jī", "Kê", "Con gà", "Động vật / Animals"],
    ["猪", "豬", "zhū", "Trư", "Con lợn, heo", "Động vật / Animals"],
    ["田", "田", "tián", "Điền", "Ruộng đất, đồng ruộng", "Thiên nhiên / Nature"],
    ["云", "雲", "yún", "Vân", "Mây", "Thiên nhiên / Nature"],
    ["电", "電", "diàn", "Điện", "Điện, chớp", "Thiên nhiên / Nature"],
    ["光", "光", "guāng", "Quang", "Ánh sáng", "Thiên nhiên / Nature"],
    ["星", "星", "xīng", "Tinh", "Ngôi sao", "Thiên nhiên / Nature"],
    ["空", "空", "kōng", "Không", "Bầu trời, trống rỗng", "Thiên nhiên / Nature"],
    ["笑", "笑", "xiào", "Tiếu", "Cười, mỉm cười", "Hành động / Actions"],
    ["哭", "哭", "kū", "Khốc", "Khóc", "Hành động / Actions"],
    ["走", "走", "zǒu", "Tẩu", "Đi, chạy", "Hành động / Actions"],
    ["叫", "叫", "jiào", "Khiếu", "Gọi, kêu lên, tên là", "Hành động / Actions"],
    ["问", "問", "wèn", "Vấn", "Hỏi", "Hành động / Actions"],
    ["答", "答", "dá", "Đáp", "Trả lời", "Hành động / Actions"],
    ["给", "給", "gěi", "Cấp", "Cho, biếu, đưa cho", "Hành động / Actions"],
    ["用", "用", "yòng", "Dụng", "Dùng, sử dụng", "Hành động / Actions"],
    ["要", "要", "yào", "Yếu", "Muốn, cần, phải", "Cảm xúc / Emotions"],
    ["爱", "愛", "ài", "Ái", "Yêu, yêu thương", "Cảm xúc / Emotions"],
    ["怕", "怕", "pà", "Phạ", "Sợ, lo sợ", "Cảm xúc / Emotions"],
    ["高", "高", "gāo", "Cao", "Cao ráo, cao lớn", "Tính từ / Adjectives"],
    ["矮", "矮", "ǎi", "Ải", "Thấp, lùn", "Tính từ / Adjectives"],
    ["长", "長", "cháng", "Trường", "Dài, lâu dài", "Tính từ / Adjectives"],
    ["短", "短", "duǎn", "Đoản", "Ngắn", "Tính từ / Adjectives"],
    ["胖", "胖", "pàng", "Bàn", "Mập, béo", "Tính từ / Adjectives"],
    ["瘦", "瘦", "shòu", "Sấu", "Gầy, ốm", "Tính từ / Adjectives"],
    ["美", "美", "měi", "Mỹ", "Đẹp, mỹ lệ", "Tính từ / Adjectives"],
    ["丑", "醜", "chǒu", "Xú", "Xấu xí", "Tính từ / Adjectives"],
    ["新", "新", "xīn", "Tân", "Mới", "Tính từ / Adjectives"],
    ["旧", "舊", "jiù", "Cựu", "Cũ", "Tính từ / Adjectives"],
    ["东", "東", "dōng", "Đông", "Phía Đông", "Vị trí / Position"],
    ["百", "百", "bǎi", "Bách", "Trăm (100)", "Số từ / Numbers"],
    ["千", "千", "qiān", "Thiên", "Nghìn (1000)", "Số từ / Numbers"],
    ["万", "萬", "wàn", "Vạn", "Mười nghìn (10000)", "Số từ / Numbers"],
    ["亿", "億", "yì", "Ức", "Trăm triệu", "Số từ / Numbers"],
    ["春", "春", "chūn", "Xuân", "Mùa xuân", "Thời gian / Time"],
    ["夏", "夏", "xià", "Hạ", "Mùa hè", "Thời gian / Time"],
    ["秋", "秋", "qiū", "Thu", "Mùa thu", "Thời gian / Time"],
    ["冬", "冬", "dōng", "Đông", "Mùa đông", "Thời gian / Time"],
    ["分", "分", "fēn", "Phân", "Phút, chia ra", "Thời gian / Time"],
    ["秒", "秒", "miǎo", "Miểu", "Giây (đơn vị thời gian)", "Thời gian / Time"],
    ["早", "早", "zǎo", "Tảo", "Sớm", "Thời gian / Time"],
    ["晚", "晚", "wǎn", "Vãn", "Muộn, tối", "Thời gian / Time"],
    ["纸", "紙", "zhǐ", "Chỉ", "Giấy", "Đồ dùng / Items"],
    ["门", "門", "mén", "Môn", "Cửa, lối ra vào", "Đồ dùng / Items"],
    ["床", "床", "chuáng", "Sàng", "Cái giường", "Đồ dùng / Items"],
    ["灯", "燈", "dēng", "Đăng", "Cái đèn, ánh sáng", "Đồ dùng / Items"],
    ["镜", "鏡", "jìng", "Kính", "Cái gương", "Đồ dùng / Items"],
    ["歌", "歌", "gē", "Ca", "Bài hát", "Giải trí / Entertainment"],
    ["诗", "詩", "shī", "Thi", "Bài thơ", "Giải trí / Entertainment"],
    ["琴", "琴", "qín", "Cầm", "Đàn (nhạc cụ)", "Giải trí / Entertainment"],
    ["棋", "棋", "qí", "Kỳ", "Cờ (chơi cờ)", "Giải trí / Entertainment"],
    ["香", "香", "xiāng", "Hương", "Thơm, hương thơm", "Tính từ / Adjectives"],
    ["臭", "臭", "chòu", "Xú", "Hôi, thối", "Tính từ / Adjectives"],
    ["冷", "冷", "lěng", "Lãnh", "Lạnh", "Tính từ / Adjectives"],
    ["热", "熱", "rè", "Nhiệt", "Nóng", "Tính từ / Adjectives"],
    ["快", "快", "kuài", "Khoái", "Nhanh, mau lẹ, vui vẻ", "Tính từ / Adjectives"],
    ["慢", "慢", "màn", "Mạn", "Chậm, từ từ", "Tính từ / Adjectives"],
    ["难", "難", "nán", "Nan", "Khó khăn, gian nan", "Tính từ / Adjectives"],
    ["易", "易", "yì", "Dịch", "Dễ, dễ dàng, thay đổi", "Tính từ / Adjectives"],
    ["真", "真", "zhēn", "Chân", "Thật, chân thực", "Tính từ / Adjectives"],
    ["假", "假", "jiǎ", "Giả", "Giả, giả định", "Tính từ / Adjectives"],
    ["对", "對", "duì", "Đối", "Đúng, đối phó, đối chiếu", "Tính từ / Adjectives"],
    ["错", "錯", "cuò", "Thác", "Sai, lỗi sai", "Tính từ / Adjectives"],
    ["黑", "黑", "hēi", "Hắc", "Màu đen, tối tăm", "Màu sắc / Colors"],
    ["白", "白", "bái", "Bạch", "Màu trắng, trống không", "Màu sắc / Colors"],
    ["红", "紅", "hóng", "Hồng", "Màu đỏ", "Màu sắc / Colors"],
    ["黄", "黃", "huáng", "Hoàng", "Màu vàng", "Màu sắc / Colors"],
    ["蓝", "藍", "lán", "Lam", "Màu xanh lam", "Màu sắc / Colors"],
    ["绿", "綠", "lǜ", "Lục", "Màu xanh lục", "Màu sắc / Colors"],
    ["开", "開", "kāi", "Khai", "Mở, khởi đầu", "Hành động / Actions"],
    ["关", "關", "guān", "Quan", "Đóng, khép, quan hệ", "Hành động / Actions"],
    ["爬", "爬", "pá", "Ba", "Leo, trèo, bò", "Hành động / Actions"],
    ["跳", "跳", "tiào", "Khiêu", "Nhảy, bật lên", "Hành động / Actions"],
    ["唱", "唱", "chàng", "Xướng", "Hát, xướng lên", "Hành động / Actions"],
    ["吹", "吹", "chuī", "Xuy", "Thổi, khoác lác", "Hành động / Actions"],
    ["打", "打", "dǎ", "Đả", "Đánh, gõ, chơi bóng", "Hành động / Actions"],
    ["住", "住", "zhù", "Trú", "Trú ngụ, ở, dừng lại", "Hành động / Actions"],
    ["行", "行", "xíng", "Hành", "Đi, được, thực hiện", "Hành động / Actions"],
    ["听写", "聽寫", "tīngxiě", "Thính tả", "Nghe viết, chính tả", "Học tập / Study"],
    ["读书", "讀書", "dúshū", "Độc thư", "Đọc sách, học tập", "Học tập / Study"],
    ["中文", "中文", "Zhōngwén", "Trung văn", "Chữ Trung Quốc, tiếng Trung", "Ngôn ngữ / Language"],
    ["英文", "英文", "Yīngwén", "Anh văn", "Chữ Tiếng Anh, tiếng Anh", "Ngôn ngữ / Language"],
    ["中国茶", "中國茶", "Zhōngguóchá", "Trung quốc trà", "Trà Trung Quốc", "Đồ ăn uống / Food & Drinks"],
    ["花茶", "花茶", "huāchá", "Hoa trà", "Trà hoa quả/hoa nhài", "Đồ ăn uống / Food & Drinks"],
    ["好喝", "好喝", "hǎohē", "Hảo hát", "Uống ngon", "Đồ ăn uống / Food & Drinks"],
    ["好吃", "好吃", "hǎochī", "Hảo ngật", "Ăn ngon", "Đồ ăn uống / Food & Drinks"],
    ["面条", "麵條", "miàntiáo", "Miến điều", "Sợi mì, món mì", "Đồ ăn uống / Food & Drinks"],
    ["水饺", "水餃", "shuǐjiǎo", "Thủy giảo", "Bánh sủi cảo", "Đồ ăn uống / Food & Drinks"],
    ["好人", "好人", "hǎorén", "Hảo nhân", "Người tốt", "Con người / People"],
    ["坏人", "壞人", "huàirén", "Hoại nhân", "Người xấu", "Con người / People"],
    ["老人", "老人", "lǎorén", "Lão nhân", "Người già, cụ già", "Con người / People"],
    ["小人", "小人", "xiǎorén", "Tiểu nhân", "Kẻ tiểu nhân, trẻ nhỏ", "Con người / People"],
    ["大人", "大人", "dàrén", "Đại nhân", "Người lớn, đại nhân", "Con người / People"]
  ],
  2: [
    ["晴天", "晴天", "qíngtiān", "Tình thiên", "Ngày nắng, trời đẹp", "Thiên nhiên / Nature"],
    ["阴天", "陰天", "yīntiān", "Âm thiên", "Ngày u ám, nhiều mây", "Thiên nhiên / Nature"],
    ["牛奶", "牛奶", "niúnǎi", "Ngưu nãi", "Sữa bò", "Đồ ăn uống / Food & Drinks"],
    ["羊肉", "羊肉", "yángròu", "Dương nhục", "Thịt dê", "Đồ ăn uống / Food & Drinks"],
    ["手提包", "手提包", "shǒutíbāo", "Thủ đề bao", "Túi xách tay", "Đồ dùng / Items"],
    ["眼镜", "眼鏡", "yǎnjìng", "Nhãn kính", "Kính mắt", "Đồ dùng / Items"],
    ["钥匙", "鑰匙", "yàoshi", "Thược thi", "Chìa khóa", "Đồ dùng / Items"],
    ["游泳", "游泳", "yóuyǒng", "Du vịnh", "Bơi lội", "Hành động / Actions"],
    ["妻子", "妻子", "qīzi", "Thê tử", "Vợ, người vợ", "Con người / People"],
    ["丈夫", "丈夫", "zhàngfu", "Trượng phu", "Chồng, người chồng", "Con người / People"],
    ["哥哥", "哥哥", "gēge", "Ca ca", "Anh trai", "Con người / People"],
    ["姐姐", "姐姐", "jiějie", "Tỷ tỷ", "Chị gái", "Con người / People"],
    ["弟弟", "弟弟", "dìdi", "Đệ đệ", "Em trai", "Con người / People"],
    ["妹妹", "妹妹", "mèimei", "Muội muội", "Em gái", "Con người / People"],
    ["孩子", "孩子", "háizi", "Hài tử", "Đứa trẻ, con cái", "Con người / People"],
    ["旅馆", "旅館", "lǚguǎn", "Lữ quán", "Nhà nghỉ, khách sạn nhỏ", "Địa điểm / Places"],
    ["分钟", "分鐘", "fēnzhōng", "Phân chung", "Phút (thời gian)", "Thời gian / Time"],
    ["因为", "因為", "yīnwèi", "Nhân vị", "Bởi vì, vì", "Liên từ / Conjunctions"],
    ["所以", "所以", "suǒyǐ", "Sở dĩ", "Cho nên, vì vậy", "Liên từ / Conjunctions"],
    ["但是", "但是", "dànshì", "Đản thị", "Nhưng, nhưng mà", "Liên từ / Conjunctions"],
    ["虽然", "although", "suīrán", "Tuy nhiên", "Mặc dù, tuy rằng", "Liên từ / Conjunctions"],
    ["累", "累", "lèi", "Lũy", "Mệt mỏi, mệt nhọc", "Tính từ / Adjectives"],
    ["容易", "容易", "róngyì", "Dung dịch", "Dễ dàng, dung dị", "Tính từ / Adjectives"],
    ["远", "遠", "yuǎn", "Viễn", "Xa xôi", "Tính từ / Adjectives"],
    ["近", "近", "jìn", "Cận", "Gần gũi", "Tính từ / Adjectives"],
    ["忙", "忙", "máng", "Mang", "Bận rộn", "Tính từ / Adjectives"],
    ["脏", "髒", "zāng", "Tạng", "Bẩn thỉu, dơ bẩn", "Tính từ / Adjectives"],
    ["洗手", "洗手", "xǐshǒu", "Tẩy thủ", "Rửa tay", "Hành động / Actions"],
    ["看书", "看書", "kànshū", "Khán thư", "Đọc sách", "Hành động / Actions"],
    ["买书", "買書", "mǎishū", "Mãi thư", "Mua sách", "Hành động / Actions"],
    ["听歌", "聽歌", "tīnggē", "Thính ca", "Nghe hát, nghe nhạc", "Hành động / Actions"],
    ["写字", "寫字", "xiězì", "Tả tự", "Viết chữ", "Hành động / Actions"],
    ["唱歌", "唱歌", "chànggē", "Xướng ca", "Hát, ca hát", "Hành động / Actions"],
    ["跳舞", "跳舞", "tiàowǔ", "Khiêu vũ", "Nhảy múa, khiêu vũ", "Hành động / Actions"],
    ["跑步", "跑步", "pǎobù", "Bào bộ", "Chạy bộ", "Hành động / Actions"],
    ["打球", "打球", "dǎqiú", "Đả cầu", "Chơi bóng", "Hành động / Actions"],
    ["踢球", "踢球", "tīqiú", "Đá cầu", "Đá bóng", "Hành động / Actions"],
    ["看病", "看病", "kànbìng", "Khán bệnh", "Khám bệnh", "Hành động / Actions"],
    ["吃药", "吃藥", "chīyào", "Ngật dược", "Uống thuốc", "Hành động / Actions"],
    ["住院", "住院", "zhùyuàn", "Trú viện", "Nằm viện", "Hành động / Actions"],
    ["出院", "出院", "chūyuàn", "Xuất viện", "Xuất viện, ra viện", "Hành động / Actions"],
    ["刮风", "刮風", "guāfēng", "Quát phong", "Gió thổi", "Thiên nhiên / Nature"],
    ["走下路", "走下路", "zǒu xiàlù", "Tẩu hạ lộ", "Đi xuống đường", "Hành động / Actions"],
    ["送水果", "送水果", "sòng shuǐguǒ", "Tống thủy quả", "Tặng trái cây", "Hành động / Actions"],
    ["吃牛肉", "吃牛肉", "chī niúròu", "Ngật ngưu nhục", "Ăn thịt bò", "Hành động / Actions"],
    ["吃鸡肉", "吃雞肉", "chī jīròu", "Ngật kê nhục", "Ăn thịt gà", "Đồ ăn uống / Food & Drinks"],
    ["吃猪肉", "吃豬肉", "chī zhūròu", "Ngật trư nhục", "Ăn thịt lợn", "Đồ ăn uống / Food & Drinks"],
    ["喝果汁", "喝果汁", "hē guǒzhī", "Hát quả trấp", "Uống nước trái cây", "Đồ ăn uống / Food & Drinks"],
    ["喝牛奶", "喝牛奶", "hē niúnǎi", "Hát ngưu nãi", "Uống sữa bò", "Đồ ăn uống / Food & Drinks"],
    ["吃水果", "吃水果", "chī shuǐguǒ", "Ngật thủy quả", "Ăn hoa quả", "Đồ ăn uống / Food & Drinks"],
    ["红苹果", "紅蘋果", "hóng píngguǒ", "Hồng bình quả", "Quả táo đỏ", "Đồ ăn uống / Food & Drinks"],
    ["大西瓜", "大西瓜", "dà xīguā", "Đại tây qua", "Quả dưa hấu to", "Đồ ăn uống / Food & Drinks"],
    ["喝热水", "喝熱水", "hē rèshuǐ", "Hát nhiệt thủy", "Uống nước nóng", "Đồ ăn uống / Food & Drinks"],
    ["写字笔", "寫字筆", "xiězìbǐ", "Tả tự bút", "Bút viết chữ", "Đồ dùng / Items"],
    ["大书包", "大書包", "dà shūbāo", "Đại thư bao", "Cặp sách to", "Đồ dùng / Items"],
    ["男学生", "男學生", "nán xuéshēng", "Nam học sinh", "Nam học sinh", "Con người / People"],
    ["女学生", "女學生", "nǚ xuéshēng", "Nữ học sinh", "Nữ học sinh", "Con người / People"],
    ["男老师", "男老師", "nán lǎoshī", "Nam lão sư", "Thầy giáo", "Con người / People"],
    ["女老师", "女老師", "nǚ lǎoshī", "Nữ lão sư", "Cô giáo", "Con người / People"],
    ["老朋友", "老朋友", "lǎo péngyou", "Lão bằng hữu", "Bạn cũ", "Con người / People"],
    ["好朋友", "好朋友", "hǎo péngyou", "Hảo bằng hữu", "Bạn tốt", "Con người / People"],
    ["男朋友", "男朋友", "nán péngyou", "Nam bằng hữu", "Bạn trai", "Con người / People"],
    ["女朋友", "女朋友", "nǚ péngyou", "Nữ bằng hữu", "Bạn gái", "Con người / People"],
    ["小学生", "小學生", "xiǎo xuéshēng", "Tiểu học sinh", "Học sinh tiểu học", "Con người / People"],
    ["大学生", "大學生", "dà xuéshēng", "Đại học sinh", "Sinh viên đại học", "Con người / People"],
    ["中国话", "中國話", "Zhōngguóhuà", "Trung quốc thoại", "Tiếng Trung Quốc", "Ngôn ngữ / Language"],
    ["说中文", "說中文", "shuō Zhōngwén", "Thuyết trung văn", "Nói tiếng Trung", "Hành động / Actions"],
    ["写汉字", "寫漢字", "xiě Hànzì", "Tả Hán tự", "Viết chữ Hán", "Hành động / Actions"],
    ["坐火车", "坐火車", "zuò huǒchē", "Tọa hỏa xa", "Đi tàu hỏa", "Hành động / Actions"],
    ["坐飞机", "坐飛機", "zuò fēijī", "Tọa phi cơ", "Đi máy bay", "Hành động / Actions"],
    ["开汽车", "開汽車", "kāi qìchē", "Khai khí xa", "Lái xe ô tô", "Hành động / Actions"],
    ["大教室", "大教室", "dà jiàoshì", "Đại giáo thất", "Phòng học lớn", "Địa điểm / Places"],
    ["大医院", "大醫院", "dà yīyuàn", "Đại y viện", "Bệnh viện lớn", "Địa điểm / Places"],
    ["买门票", "買門票", "mǎi ménpiào", "Mãi môn phiếu", "Mua vé vào cửa", "Hành động / Actions"],
    ["买车票", "買車票", "mǎi chēpiào", "Mãi xa phiếu", "Mua vé xe", "Hành động / Actions"],
    ["买机票", "買機票", "mǎi jīpiào", "Mãi cơ phiếu", "Mua vé máy bay", "Hành động / Actions"],
    ["回学校", "回學校", "huí xuéxiào", "Hồi học hiệu", "Về trường", "Hành động / Actions"],
    ["出门口", "出門口", "chū ménkǒu", "Xuất môn khẩu", "Ra cửa, đi ra cửa", "Hành động / Actions"],
    ["下大雨", "下大雨", "xià dàyǔ", "Hạ đại vũ", "Mưa to", "Thiên nhiên / Nature"],
    ["下大雪", "下大雪", "xià dàxuě", "Hạ đại tuyết", "Tuyết rơi dày", "Thiên nhiên / Nature"],
    ["下小雨", "下小雨", "xià xiǎoyǔ", "Hạ tiểu vũ", "Mưa nhỏ, mưa lâm thâm", "Thiên nhiên / Nature"],
    ["下小雪", "下小雪", "xià xiǎoxuě", "Hạ tiểu tuyết", "Tuyết rơi nhẹ", "Thiên nhiên / Nature"],
    ["走大路", "走大路", "zǒu dàlù", "Tẩu đại lộ", "Đi đường lớn", "Hành động / Actions"],
    ["走小路", "走小路", "zǒu xiǎolù", "Tẩu tiểu lộ", "Đi đường nhỏ, ngõ nhỏ", "Hành động / Actions"],
    ["上学", "上學", "shàngxué", "Thượng học", "Đi học", "Hành động / Actions"],
    ["放学", "放學", "fàngxué", "Phóng học", "Tan học", "Hành động / Actions"],
    ["上班", "上班", "shàngbān", "Thượng ban", "Đi làm", "Hành động / Actions"],
    ["下班", "下班", "xiàbān", "Hạ ban", "Tan làm", "Hành động / Actions"],
    ["找工作", "找工作", "zhǎo gōngzuò", "Thảo công tác", "Tìm việc làm", "Hành động / Actions"],
    ["做工作", "做工作", "zuò gōngzuò", "Tác công tác", "Làm việc", "Hành động / Actions"],
    ["出差", "出差", "chūchāi", "Xuất sai", "Đi công tác", "Hành động / Actions"],
    ["打电话", "打電話", "dǎ diànhuà", "Đả điện thoại", "Gọi điện thoại", "Hành động / Actions"],
    ["听电话", "聽電話", "tīng diànhuà", "Thính điện thoại", "Nghe điện thoại", "Hành động / Actions"],
    ["看电视", "看電視", "kàn diànshì", "Khán điện thị", "Xem tivi", "Hành động / Actions"],
    ["看电影", "看電影", "kàn diànyǐng", "Khán điện ảnh", "Xem phim", "Hành động / Actions"],
    ["用电脑", "用電腦", "yòng diànnǎo", "Dụng điện não", "Dùng máy tính", "Hành động / Actions"],
    ["玩游戏", "玩遊戲", "wán yóuxì", "Ngoạn du hí", "Chơi game", "Giải trí / Entertainment"],
    ["买电脑", "買電腦", "mǎi diànnǎo", "Mãi điện não", "Mua máy tính", "Hành động / Actions"],
    ["买手机", "買手機", "mǎi shǒujī", "Mãi thủ cơ", "Mua điện thoại", "Hành động / Actions"],
    ["写邮件", "寫郵件", "xiě yóujiàn", "Tả bưu kiện", "Viết email", "Hành động / Actions"]
  ],
  3: [
    ["办公室", "辦公室", "bàngōngshì", "Biện công thất", "Văn phòng làm việc", "Địa điểm / Places"],
    ["地铁", "地鐵", "dìtiě", "Địa thiết", "Tàu điện ngầm", "Giao thông / Traffic"],
    ["街道", "街道", "jiēdào", "Nhai đạo", "Đường phố, khu phố", "Địa điểm / Places"],
    ["聪明", "聰明", "cōngming", "Thông minh", "Thông minh, lanh lợi", "Tính từ / Adjectives"],
    ["奇怪", "奇怪", "qíguài", "Kỳ quái", "Kỳ quái, lạ lùng", "Tính từ / Adjectives"],
    ["新鲜", "新鮮", "xīnxiān", "Tân tiên", "Tươi ngon, tươi mát, mới mẻ", "Tính từ / Adjectives"],
    ["机会", "機會", "jīhuì", "Cơ hội", "Cơ hội, thời cơ", "Danh từ / Nouns"],
    ["练习", "練習", "liànxí", "Luyện tập", "Luyện tập, thực hành", "Hành động / Actions"],
    ["结婚", "結婚", "jiéhūn", "Kết hôn", "Kết hôn, lập gia đình", "Trạng thái / States"],
    ["搬家", "搬家", "bānjiā", "Ban gia", "Chuyển nhà", "Hành động / Actions"],
    ["打扫", "打掃", "dǎsǎo", "Đả tảo", "Quét dọn, dọn dẹp", "Hành động / Actions"],
    ["选择", "選擇", "xuǎnzé", "Tuyển trạch", "Lựa chọn, tuyển chọn", "Hành động / Actions"],
    ["同意", "同意", "tóngyì", "Đồng ý", "Đồng ý, nhất trí", "Hành động / Actions"],
    ["要求", "要求", "yāoqiú", "Yêu cầu", "Yêu cầu, đòi hỏi", "Hành động / Actions"],
    ["爬山", "爬山", "páshān", "Ba sơn", "Leo núi, đi leo núi", "Hành động / Actions"],
    ["洗脸", "洗臉", "xǐliǎn", "Tẩy liển", "Rửa mặt", "Hành động / Actions"],
    ["洗澡", "洗澡", "xǐzǎo", "Tẩy tảo", "Tắm, tắm rửa", "Hành động / Actions"],
    ["刷牙", "刷牙", "shuāyá", "Soát nha", "Đánh răng", "Hành động / Actions"],
    ["发烧", "發燒", "fāshāo", "Phát thiêu", "Bị sốt", "Trạng thái / States"],
    ["咳嗽", "咳嗽", "késou", "Khái thấu", "Ho", "Trạng thái / States"],
    ["感冒", "感冒", "gǎnmào", "Cảm mạo", "Cảm cúm, cảm lạnh", "Trạng thái / States"],
    ["注意", "注意", "zhùyì", "Chú ý", "Chú ý, lưu ý", "Hành động / Actions"],
    ["黑板", "黑板", "hēibǎn", "Hắc bản", "Bảng đen", "Đồ dùng / Items"],
    ["拿东西", "拿東西", "ná dôngxi", "Nã đông tây", "Cầm đồ đạc, lấy đồ", "Hành động / Actions"],
    ["放书", "放書", "fàng shū", "Phóng thư", "Đặt sách, để sách", "Hành động / Actions"],
    ["借书", "借書", "jiè shū", "Tá thư", "Mượn sách", "Hành động / Actions"],
    ["还书", "還書", "huán shū", "Hoàn thư", "Trả sách", "Hành động / Actions"],
    ["买礼物", "買禮物", "mǎi lǐwù", "Mãi lễ vật", "Mua quà tặng", "Hành động / Actions"],
    ["送礼物", "送禮物", "sòng lǐwù", "Tống lễ vật", "Tặng quà", "Hành động / Actions"],
    ["写信", "寫信", "xiěxìn", "Tả tín", "Viết thư", "Hành động / Actions"],
    ["寄信", "寄信", "jìxìn", "Ký tín", "Gửi thư", "Hành động / Actions"],
    ["听音乐", "聽音樂", "tīng yīnyuè", "Thính âm nhạc", "Nghe nhạc", "Hành động / Actions"],
    ["画画儿", "畫畫兒", "huàhuàr", "Họa họa nhi", "Vẽ tranh", "Hành động / Actions"],
    ["照相", "照相", "zhàoxiàng", "Chiếu tướng", "Chụp ảnh", "Hành động / Actions"],
    ["洗衣服", "洗衣服", "xǐ yīfu", "Tẩy y phục", "Giặt quần áo", "Hành động / Actions"],
    ["做蛋糕", "做蛋糕", "zuò dàngāo", "Tác đản cao", "Làm bánh ngọt", "Hành động / Actions"],
    ["吃蛋糕", "吃蛋糕", "chī dàngāo", "Ngật đản cao", "Ăn bánh ngọt", "Đồ ăn uống / Food & Drinks"],
    ["喝绿茶", "喝綠茶", "hē lǜchá", "Hát lục trà", "Uống trà xanh", "Đồ ăn uống / Food & Drinks"],
    ["喝红茶", "喝紅茶", "hē hóngchá", "Hát hồng trà", "Uống trà đen/hồng trà", "Đồ ăn uống / Food & Drinks"],
    ["吃香蕉", "吃香蕉", "chī xiāngjiāo", "Ngật hương tiêu", "Ăn chuối", "Đồ ăn uống / Food & Drinks"],
    ["喝啤酒", "喝啤酒", "hē píjiǔ", "Hát tì tửu", "Uống bia", "Đồ ăn uống / Food & Drinks"],
    ["吃面包", "吃麵包", "chī miànbāo", "Ngật miến bao", "Ăn bánh mì", "Đồ ăn uống / Food & Drinks"],
    ["用筷子", "用筷子", "yòng kuàizi", "Dụng khoái tử", "Dùng đũa", "Đồ dùng / Items"],
    ["洗盘子", "洗盤子", "xǐ pánzi", "Tẩy bàn tử", "Rửa đĩa", "Đồ dùng / Items"],
    ["洗碗", "洗碗", "xǐ wǎn", "Tẩy uyển", "Rửa bát", "Đồ dùng / Items"],
    ["坐电梯", "坐電梯", "zuò diàntī", "Tọa điện thang", "Đi thang máy", "Hành động / Actions"],
    ["坐地铁", "坐地鐵", "zuò dìtiě", "Tọa địa thiết", "Đi tàu điện ngầm", "Hành động / Actions"],
    ["看地图", "看地圖", "kàn dìtú", "Khán địa đồ", "Xem bản đồ", "Hành động / Actions"],
    ["办护照", "辦護照", "bàn hùzhào", "Biện hộ chiếu", "Làm hộ chiếu", "Hành động / Actions"],
    ["用信用卡", "用信用卡", "yòng xìnyòngkǎ", "Dụng tín dụng tạp", "Sử dụng thẻ tín dụng", "Đồ dùng / Items"],
    ["开空调", "開空調", "kāi kōngtiáo", "Khai không điều", "Bật điều hòa", "Hành động / Actions"],
    ["关空调", "關空調", "guān kōngtiáo", "Quan không điều", "Tắt điều hòa", "Hành động / Actions"],
    ["大公园", "大公園", "dà gōngyuán", "Đại công viên", "Công viên lớn", "Địa điểm / Places"],
    ["去银行", "去銀行", "qù yínháng", "Khứ ngân hàng", "Đi ngân hàng", "Địa điểm / Places"],
    ["去图书馆", "去圖書館", "qù túshūguǎn", "Khứ đồ thư quán", "Đi thư viện", "Địa điểm / Places"],
    ["去体育馆", "去體育館", "qù tǐyùguǎn", "Khứ thể dục quán", "Đi nhà thi đấu", "Địa điểm / Places"],
    ["大宾馆", "大賓館", "dà bīnguǎn", "Đại tân quán", "Khách sạn lớn", "Địa điểm / Places"],
    ["洗手间", "洗手間", "xǐshǒujiān", "Tẩy thủ gian", "Nhà vệ sinh", "Địa điểm / Places"],
    ["暖和天气", "暖和天氣", "nuǎnhuo tiānqì", "Noãn hòa thiên khí", "Thời tiết ấm áp", "Thiên nhiên / Nature"],
    ["安静教室", "安靜教室", "ānjìng jiàoshì", "An tĩnh giáo thất", "Lớp học yên tĩnh", "Địa điểm / Places"],
    ["干净房间", "乾淨房間", "gānjìng fángjiān", "Can tịnh phòng gian", "Căn phòng sạch sẽ", "Địa điểm / Places"],
    ["舒服衣服", "舒服衣服", "shūfu yīfu", "Thư phục y phục", "Quần áo dễ chịu", "Trang phục / Clothes"],
    ["坏习惯", "壞習慣", "huài xíguàn", "Hoại tập quán", "Thói quen xấu", "Danh từ / Nouns"],
    ["好习惯", "好習慣", "hǎo xíguàn", "Hảo tập quán", "Thói quen tốt", "Danh từ / Nouns"],
    ["提意见", "提意見", "tí yìjiàn", "Đề ý kiến", "Đưa ra ý kiến, góp ý", "Hành động / Actions"],
    ["找机会", "找機會", "zhǎo jīhuì", "Thảo cơ hội", "Tìm kiếm cơ hội", "Hành động / Actions"],
    ["做练习", "做練習", "zuò liànxí", "Tác luyện tập", "Làm bài luyện tập", "Hành động / Actions"],
    ["做计划", "做計劃", "zuò jìhuà", "Tác kế hoạch", "Lập kế hoạch", "Hành động / Actions"],
    ["定时间", "定時間", "dìng shíjiān", "Định thời gian", "Lên lịch thời gian", "Hành động / Actions"],
    ["写作业", "寫作業", "xiě zuòyè", "Tả tác nghiệp", "Viết bài tập về nhà", "Học tập / Study"],
    ["做作业", "做作業", "zuò zuòyè", "Tác tác nghiệp", "Làm bài tập về nhà", "Học tập / Study"],
    ["上大学", "上大學", "shàng dàxué", "Thượng đại học", "Học đại học", "Học tập / Study"],
    ["放假", "放假", "fàngjià", "Phóng giả", "Nghỉ lễ, được nghỉ", "Thời gian / Time"],
    ["打算", "打算", "dǎsuàn", "Đả toán", "Dự định, kế hoạch", "Hành động / Actions"],
    ["旅游鞋", "旅遊鞋", "lǚyóuxié", "Lữ du hài", "Giày du lịch/giày thể thao", "Trang phục / Clothes"],
    ["运动鞋", "運動鞋", "yùndòngxié", "Vận động hài", "Giày thể thao", "Trang phục / Clothes"],
    ["皮鞋", "皮鞋", "píxié", "Bì hài", "Giày da", "Trang phục / Clothes"],
    ["高跟鞋", "高跟鞋", "gāogēnxié", "Cao căn hài", "Giày cao gót", "Trang phục / Clothes"],
    ["大外套", "大外套", "dà wàitào", "Đại ngoại sáo", "Áo khoác to", "Trang phục / Clothes"],
    ["买裤子", "買褲子", "mǎi kùzi", "Mãi khố tử", "Mua quần", "Hành động / Actions"],
    ["穿裙子", "穿裙子", "chuān qúnzi", "Xuyên quần tử", "Mặc váy", "Hành động / Actions"],
    ["系领带", "繫領帶", "jì lǐngdài", "Hệ lĩnh đới", "Thắt cà vạt", "Hành động / Actions"],
    ["戴帽子", "戴帽子", "dài màozi", "Đới mạo tử", "Đội mũ", "Hành động / Actions"],
    ["戴眼镜", "戴眼鏡", "dài yǎnjìng", "Đới nhãn kính", "Đeo kính", "Hành động / Actions"],
    ["戴手表", "戴手錶", "dài shǒubiǎo", "Đới thủ biểu", "Đeo đồng hồ", "Hành động / Actions"],
    ["开玩笑", "開玩笑", "kāi wánxiào", "Khai ngoạn tiếu", "Nói đùa, trêu chọc", "Hành động / Actions"],
    ["讲故事", "講故事", "jiǎng gùshi", "Giảng sự cố", "Kể câu chuyện", "Hành động / Actions"],
    ["听故事", "聽故事", "tīng gùshi", "Thính sự cố", "Nghe kể chuyện", "Hành động / Actions"],
    ["有意思", "有意思", "yǒu yìsi", "Hữu ý tứ", "Thú vị, có ý nghĩa", "Tính từ / Adjectives"],
    ["没意思", "沒意思", "méi yìsi", "Một ý tứ", "Tẻ nhạt, vô vị", "Tính từ / Adjectives"],
    ["很聪明", "很聰明", "hěn cōngming", "Hận thông minh", "Rất thông minh", "Tính từ / Adjectives"],
    ["很可爱", "很可愛", "hěn kě'ài", "Hận khả ái", "Rất đáng yêu", "Tính từ / Adjectives"],
    ["很舒服", "很舒服", "hěn shūfu", "Hận thư phục", "Rất thoải mái", "Tính từ / Adjectives"],
    ["不满意", "不滿意", "bù mǎnyì", "Bất mãn ý", "Không hài lòng", "Cảm xúc / Emotions"],
    ["很生气", "很生氣", "hěn shēngqì", "Hận sinh khí", "Rất tức giận", "Cảm xúc / Emotions"],
    ["别担心", "別擔心", "bié dānxīn", "Biệt đam tâm", "Đừng lo lắng", "Cảm xúc / Emotions"],
    ["害怕鬼", "害怕鬼", "hàipà guǐ", "Hại phạ quỷ", "Sợ ma", "Cảm xúc / Emotions"],
    ["难过哭", "難過哭", "nánguò kū", "Nan quá khốc", "Buồn bã khóc lóc", "Cảm xúc / Emotions"],
    ["洗脸盆", "洗臉盆", "xǐliǎnpén", "Tẩy liển bồn", "Chậu rửa mặt", "Đồ dùng / Items"]
  ],
  4: [
    ["翻译", "翻譯", "fānyì", "Phiên dịch", "Dịch thuật, phiên dịch", "Hành động / Actions"],
    ["反对", "反對", "fǎnduì", "Phản đối", "Phản đối, không tán thành", "Hành động / Actions"],
    ["符合", "符合", "fúhé", "Phù hợp", "Phù hợp, khớp với", "Trạng thái / States"],
    ["负责", "負責", "fùzé", "Phụ trách", "Chịu trách nhiệm, phụ trách", "Hành động / Actions"],
    ["积累", "积累", "jīlěi", "Tích lũy", "Tích lũy, gom góp", "Hành động / Actions"],
    ["拒绝", "拒絕", "jùjué", "Cự tuyệt", "Từ chối, khước từ", "Hành động / Actions"],
    ["考虑", "考慮", "kǎolǜ", "Khảo lự", "Suy nghĩ, cân nhắc, khảo lự", "Nhận thức / Cognitive"],
    ["流行", "流行", "liúxíng", "Lưu hành", "Thịnh hành, phổ biến", "Tính từ / Adjectives"],
    ["批评", "批評", "pīpíng", "Phê bình", "Phê bình, khiển trách", "Hành động / Actions"],
    ["商量", "商量", "shāngliang", "Thương lượng", "Bàn bạc, thương lượng", "Hành động / Actions"],
    ["空闲", "空閒", "kòngxián", "Không nhàn", "Rảnh rỗi, nhàn hạ", "Tính từ / Adjectives"],
    ["困难", "困難", "kùnnan", "Khốn nan", "Khó khăn, gian khổ", "Tính từ / Adjectives"],
    ["懒", "懶", "lǎn", "Lãn", "Lười biếng", "Tính từ / Adjectives"],
    ["浪漫", "浪漫", "làngmàn", "Lãng mạn", "Lãng mạn", "Tính từ / Adjectives"],
    ["普及", "普及", "pǔjí", "Phổ cập", "Phổ cập, phổ biến rộng rãi", "Trạng thái / States"],
    ["轻松", "輕鬆", "qīngsōng", "Khinh tống", "Nhẹ nhàng, thoải mái, thư giãn", "Tính từ / Adjectives"],
    ["热闹", "熱鬧", "rènao", "Nhiệt náo", "Náo nhiệt, nhộn nhịp", "Tính từ / Adjectives"],
    ["深", "深", "shēn", "Thâm", "Sâu sắc, thâm sâu, màu đậm", "Tính từ / Adjectives"],
    ["顺利", "順利", "shùnlì", "Thuận lợi", "Thuận lợi, trôi chảy", "Tính từ / Adjectives"],
    ["无聊", "無聊", "wúliáo", "Vô liêu", "Nhạt nhẽo, chán ngắt, rảnh rỗi quá", "Tính từ / Adjectives"],
    ["幽默", "幽默", "yōumò", "U mặc", "Hài hước, hóm hỉnh", "Tính từ / Adjectives"],
    ["顾客", "顧客", "gùkè", "Cố khách", "Khách mua hàng, khách hàng", "Con người / People"],
    ["律师", "律師", "lǜshī", "Luật sư", "Luật sư", "Con người / People"],
    ["作者", "作者", "zuòzhě", "Tác giả", "Tác giả, người viết", "Con người / People"],
    ["师傅", "師傅", "shīfu", "Sư phụ", "Sư phụ, người thợ cả, bác tài", "Con người / People"],
    ["森林", "森林", "sēnlín", "Sâm lâm", "Rừng rậm", "Thiên nhiên / Nature"],
    ["空气", "空氣", "kōngqì", "Không khí", "Không khí, khí quyển", "Thiên nhiên / Nature"],
    ["安排时间", "安排時間", "ānpái shíjiān", "An bài thời gian", "Sắp xếp thời gian", "Hành động / Actions"],
    ["写保证书", "寫保證書", "xiě bǎozhèngshū", "Tả bảo chứng thư", "Viết giấy cam đoan/bảo lãnh", "Học tập / Study"],
    ["保护森林", "保護森林", "bǎohù sēnlín", "Bảo hộ sâm lâm", "Bảo vệ rừng", "Hành động / Actions"],
    ["报名参加", "報名參加", "bàomíng cānjiā", "Báo danh tham gia", "Đăng ký tham gia", "Hành động / Actions"],
    ["大学毕业", "大學畢業", "dàxué bìyè", "Đại học tất nghiệp", "Tốt nghiệp đại học", "Trạng thái / States"],
    ["表达谢意", "表達謝意", "biǎodá xièyì", "Biểu đạt tạ ý", "Bày tỏ lòng cảm ơn", "Giao tiếp / Communication"],
    ["填表格", "填表格", "tián biǎogé", "Điền biểu cách", "Điền vào biểu mẫu", "Học tập / Study"],
    ["表扬学生", "表揚學生", "biǎoyáng xuéshēng", "Biểu dương học sinh", "Khen ngợi học sinh", "Hành động / Actions"],
    ["戏剧表演", "戲劇表演", "xìjù biǎoyǎn", "Hí kịch biểu diễn", "Biểu diễn kịch nghệ", "Giải trí / Entertainment"],
    ["并且同意", "並且同意", "bìngqiě tóngyì", "Tịnh thả đồng ý", "Và cũng đồng ý", "Liên từ / Conjunctions"],
    ["工学博士", "工學博士", "gōngxué bóshì", "Công học bác sĩ", "Tiến sĩ kỹ thuật", "Con người / People"],
    ["不管是谁", "不管是誰", "bùguǎn shì shéi", "Bất quản thị thùy", "Bất kể là ai", "Liên từ / Conjunctions"],
    ["不仅如此", "不僅如此", "bùjǐn rúcǐ", "Bất cận như thử", "Không chỉ có thế", "Liên từ / Conjunctions"],
    ["主要部分", "主要部分", "zhǔyào bùfen", "Chủ yếu bộ phận", "Bộ phận chính", "Danh từ / Nouns"],
    ["擦黑板", "擦黑板", "cā hēibǎn", "Sát hắc bản", "Lau bảng đen", "Hành động / Actions"],
    ["猜故事", "猜故事", "cāi gùshi", "Sái sự cố", "Đoán cốt truyện", "Hành động / Actions"],
    ["建筑材料", "建築材料", "jiànzhù cáiliào", "Kiến trúc tài liệu", "Vật liệu xây dựng", "Danh từ / Nouns"],
    ["参观公园", "參觀公園", "cānguān gōngyuán", "Tham quan công viên", "Tham quan công viên", "Hành động / Actions"],
    ["差不多大", "差不多大", "chàbuduō dà", "Sai bất đa đại", "To lớn xấp xỉ nhau", "Trạng từ / Adverbs"],
    ["登长城", "登長城", "dēng Chángchéng", "Đăng trường thành", "Leo Vạn Lý Trường Thành", "Hành động / Actions"],
    ["过长江", "過長江", "guò Chángjiāng", "Quá trường giang", "Băng qua sông Trường Giang", "Hành động / Actions"],
    ["足球赛场", "足球賽場", "zúqiú sàichǎng", "Túc cầu tái trường", "Sân thi đấu bóng đá", "Địa điểm / Places"],
    ["超过千人", "超過千人", "chāoguò qiānrén", "Siêu quá thiên nhân", "Vượt quá một ngàn người", "Hành động / Actions"],
    ["事业成功", "事業成功", "shìyè chénggōng", "Sự nghiệp thành công", "Sự nghiệp thành công", "Trạng thái / States"],
    ["诚实回答", "誠實回答", "chéngshí huídá", "Thành thực hồi đáp", "Trả lời thành thật", "Giao tiếp / Communication"],
    ["不要抽烟", "不要抽煙", "búyào chōuyān", "Bất yếu trừu yên", "Đừng hút thuốc", "Hành động / Actions"],
    ["出差回来", "出差回來", "chūchāi huílái", "Xuất sai hồi lai", "Đi công tác về", "Hành động / Actions"],
    ["出发时间", "出發時間", "chūfā shíjiān", "Xuất phát thời gian", "Thời gian xuất phát", "Thời gian / Time"],
    ["出生年月日", "出生年月日", "chūshēng nián yuè rì", "Xuất sinh niên nguyệt nhật", "Ngày tháng năm sinh", "Thời gian / Time"],
    ["问题出现", "問題出現", "wèntí chūxiàn", "Vấn đề xuất hiện", "Vấn đề nảy sinh", "Trạng thái / States"],
    ["粗心大意", "粗心大意", "cūxīn dàyì", "Thô tâm đại ý", "Sơ ý cẩu thả", "Tính từ / Adjectives"],
    ["银行存款", "銀行存款", "yínháng cúnkuǎn", "Ngân hàng tồn khoản", "Tiền gửi tiết kiệm ngân hàng", "Danh từ / Nouns"],
    ["犯错误", "犯錯誤", "fàn cuòwù", "Phạm thác ngộ", "Phạm sai lầm", "Hành động / Actions"],
    ["标准答案", "標準答案", "biāozhǔ dá'àn", "Tiêu chuẩn đáp án", "Đáp án tiêu chuẩn/chính xác", "Danh từ / Nouns"],
    ["仔细打扮", "仔細打扮", "zǐxì dǎban", "Tử tế đả ban", "Trang điểm kỹ càng/diện đồ", "Hành động / Actions"],
    ["打扰人家", "打擾人家", "dǎrǎo rénjia", "Đả nhiễu nhân gia", "Quấy rầy người khác", "Hành động / Actions"],
    ["打印文件", "打印文件", "dǎyìn wénjiàn", "Đả ấn văn kiện", "In ấn tài liệu", "Hành động / Actions"],
    ["商店打折", "商店打折", "shāngdiàn dǎzhé", "Thương điếm đả chiết", "Cửa hàng giảm giá", "Hành động / Actions"],
    ["生病打针", "生病打針", "shēngbìng dǎzhēn", "Sinh bệnh đả châm", "Bị ốm chích thuốc", "Hành động / Actions"],
    ["大概不错", "大概不錯", "dàgài búcuò", "Đại khái bất thác", "Đại khái là đúng/tốt", "Trạng từ / Adverbs"],
    ["中国大使馆", "中國大使館", "Zhōngguó dàshǐguǎn", "Trung quốc đại sứ quán", "Đại sứ quán Trung Quốc", "Địa điểm / Places"],
    ["大约一万", "大約一萬", "dàyuē yīwàn", "Đại ước nhất vạn", "Ước chừng mười ngàn", "Trạng từ / Adverbs"],
    ["班级代表", "班級代表", "bānjí dàibiǎo", "Ban cấp đại biểu", "Đại diện của lớp học", "Con người / People"],
    ["代替别人", "代替別人", "dàitì biéren", "Đại thế biệt nhân", "Thay thế người khác", "Hành động / Actions"],
    ["请看大夫", "請看大夫", "qǐng kàn dàifu", "Thỉnh khán đại phu", "Hãy đi khám bác sĩ", "Hành động / Actions"],
    ["银行贷款", "銀行貸款", "yínháng dàikuǎn", "Ngân hàng thải khoản", "Khoản vay ngân hàng", "Danh từ / Nouns"],
    ["当时情况", "當時情況", "dāngshí qíngkuàng", "Đương thời tình huống", "Tình hình lúc bấy giờ", "Danh từ / Nouns"],
    ["切菜刀", "切菜刀", "qiēcàidāo", "Thiết thái đao", "Dao thái rau/món ăn", "Đồ dùng / Items"],
    ["旅行社导游", "旅行社導遊", "lǚxíngshè dǎoyóu", "Lữ hành xã đạo du", "Hướng dẫn viên du lịch hãng", "Con người / People"],
    ["到处都是", "到處都是", "dàochù dōu shì", "Đáo xứ đô thị", "Khắp nơi đều là", "Vị trí / Position"],
    ["到底为什么", "到底為什麼", "dàodǐ wèishénme", "Đáo để vi thập ma", "Rốt cuộc là tại sao", "Trạng từ / Adverbs"],
    ["向他道歉", "向他道歉", "xiàng tā dàoqiàn", "Hướng tha đạo khiếm", "Xin lỗi anh ấy", "Hành động / Actions"],
    ["得意洋洋", "得意洋洋", "déyì yángyáng", "Đắc ý dương dương", "Đắc ý tự mãn vểnh râu", "Cảm xúc / Emotions"],
    ["换登机牌", "換登機牌", "huàn dēngjīpái", "Hoán đăng cơ bài", "Đổi thẻ lên máy bay", "Hành động / Actions"],
    ["耐心等待", "耐心等待", "nàixīn děngdài", "Nại tâm đẳng đãi", "Kiên nhẫn chờ đợi", "Hành động / Actions"],
    ["低着头", "低著頭", "dī zhe tóu", "Đê trứ đầu", "Cúi gằm đầu xuống", "Hành động / Actions"],
    ["月底时间", "月底時間", "yuèdǐ shíjiān", "Nguyệt để thời gian", "Thời điểm cuối tháng", "Thời gian / Time"],
    ["地球母亲", "地球母親", "dìqiú mǔqīn", "Địa cầu mẫu thân", "Mẹ Trái Đất", "Thiên nhiên / Nature"],
    ["家庭地址", "家庭地址", "jiātíng dìzhǐ", "Gia đình địa chỉ", "Địa chỉ gia đình", "Danh từ / Nouns"],
    ["社会调查", "社會調查", "shèhuì diàochá", "Xã hội điều tra", "Khảo sát xã hội", "Hành động / Actions"],
    ["动作漂亮", "動作漂亮", "dòngzuò piàoliang", "Động tác phiêu lượng", "Động tác đẹp mắt", "Tính từ / Adjectives"],
    ["堵车厉害", "堵車厲害", "dǔchē lìhai", "Đổ xa lệ hại", "Kẹt xe dữ dội", "Giao thông / Traffic"],
    ["肚子疼", "肚子疼", "dùzi téng", "Đỗ tử đông", "Đau bụng", "Trạng thái / States"],
    ["发短信", "發短信", "fā duǎnxìn", "Phát đoản tín", "Gửi tin nhắn điện thoại", "Hành động / Actions"]
  ],
  5: [
    ["财产", "財產", "cáichǎn", "Tài sản", "Tài sản, của cải", "Danh từ / Nouns"],
    ["成果", "成果", "chéngguǒ", "Thành quả", "Thành quả, kết quả đạt được", "Danh từ / Nouns"],
    ["程序", "程序", "chéngxù", "Trình tự", "Quy trình, trình tự, chương trình", "Danh từ / Nouns"],
    ["充电器", "充電器", "chōngdiànqì", "Sung điện khí", "Cục sạc, bộ sạc pin", "Đồ dùng / Items"],
    ["抽屉", "抽屜", "chōuti", "Trừu thế", "Ngăn kéo bàn", "Đồ dùng / Items"],
    ["导演", "導演", "dǎoyǎn", "Đạo diễn", "Đạo diễn điện ảnh/sân khấu", "Con người / People"],
    ["敌人", "敵人", "dírén", "Địch nhân", "Kẻ thù, quân địch", "Con người / People"],
    ["地位", "地位", "dìwèi", "Địa vị", "Địa vị xã hội, vị trí", "Danh từ / Nouns"],
    ["逗", "逗", "dòu", "Đậu", "Trêu chọc, buồn cười, khôi hài", "Tính từ / Adjectives"],
    ["范围", "範圍", "fànwéi", "Phạm vi", "Phạm vi, giới hạn", "Danh từ / Nouns"],
    ["风景", "風景", "fēngjǐng", "Phong cảnh", "Phong cảnh, cảnh đẹp", "Thiên nhiên / Nature"],
    ["巨大", "巨大", "jùdà", "Cự đại", "Khổng lồ, to lớn vĩ đại", "Tính từ / Adjectives"],
    ["乐观", "樂觀", "lèguān", "Lạc quan", "Lạc quan, yêu đời", "Cảm xúc / Emotions"],
    ["敏感", "敏感", "mǐngǎn", "Mẫn cảm", "Nhạy cảm, mẫn cảm", "Tính từ / Adjectives"],
    ["片面", "片面", "piànmiàn", "Phiến diện", "Phiến diện, một chiều", "Tính từ / Adjectives"],
    ["深刻", "深刻", "shēnkè", "Thâm khắc", "Sâu sắc, khắc sâu tâm trí", "Tính từ / Adjectives"],
    ["舒适", "舒適", "shūshì", "Thư thích", "Thoải mái, tiện nghi, dễ chịu", "Tính từ / Adjectives"],
    ["温和", "溫和", "wēnhé", "Ôn hòa", "Ôn hòa, dịu dàng, ôn đới", "Tính từ / Adjectives"],
    ["概念", "概念", "gàiniàn", "Khái niệm", "Khái niệm, ý niệm", "Nhận thức / Cognitive"],
    ["改善", "改善", "gǎishàn", "Cải thiện", "Cải thiện, làm tốt lên", "Hành động / Actions"],
    ["改革", "改革", "gǎigé", "Cải cách", "Cải cách thể chế/kinh tế", "Hành động / Actions"],
    ["干涉", "干涉", "gānshè", "Can thiệp", "Can thiệp, xía vào chuyện người", "Hành động / Actions"],
    ["独特", "独特", "dútè", "Độc đặc", "Độc đáo, đặc sắc riêng biệt", "Tính từ / Adjectives"],
    ["感激", "感激", "gǎnjī", "Cảm kích", "Cảm kích, biết ơn sâu sắc", "Cảm xúc / Emotions"],
    ["港口", "港口", "gǎngkǒu", "Cảng khẩu", "Hải cảng, bến cảng", "Địa điểm / Places"],
    ["高级", "高級", "gāojí", "Cao cấp", "Cao cấp, thượng hạng, chất lượng", "Tính từ / Adjectives"],
    ["个性", "個性", "gèxìng", "Cá tính", "Cá tính, tính cách cá nhân", "Danh từ / Nouns"],
    ["各种各样", "各種各樣", "gè zhǒng gè yàng", "Các chủng các dạng", "Đủ loại, đa dạng, phong phú", "Tính từ / Adjectives"],
    ["工具", "工具", "gōngjù", "Công cụ", "Công cụ, dụng cụ làm việc", "Đồ dùng / Items"],
    ["工业", "工業", "gōngyè", "Công nghiệp", "Công nghiệp chế tạo", "Danh từ / Nouns"],
    ["公布", "公布", "gōngbù", "Công công", "Công bố rộng rãi, công khai", "Hành động / Actions"],
    ["公开", "公開", "gōngkāi", "Công khai", "Công khai, minh bạch rộng rãi", "Hành động / Actions"],
    ["公寓", "公寓", "gōngyù", "Công ngự", "Căn hộ chung cư, nhà tập thể", "Địa điểm / Places"],
    ["公元", "公元", "gōngyuán", "Công nguyên", "Công nguyên (kỷ nguyên lịch)", "Thời gian / Time"],
    ["公主", "公主", "gōngzhǔ", "Công chúa", "Công chúa nhà vua", "Con người / People"],
    ["功能", "功能", "gōngnéng", "Công năng", "Tính năng, chức năng sử dụng", "Danh từ / Nouns"],
    ["共同", "共同", "gòngtóng", "Cộng đồng", "Chung, cùng nhau, cộng tác", "Tính từ / Adjectives"],
    ["贡献", "貢獻", "gòngxiàn", "Cống hiến", "Cống hiến, đóng góp công lao", "Hành động / Actions"],
    ["沟通", "溝通", "gōutōng", "Câu thông", "Giao tiếp, kết nối, trao đổi", "Hành động / Actions"],
    ["骨头", "骨頭", "gǔtou", "Cốt đầu", "Khúc xương, bộ xương", "Danh từ / Nouns"],
    ["固定", "固定", "gùdìng", "Cố định", "Cố định, giữ nguyên không đổi", "Trạng thái / States"],
    ["顾问", "顧問", "gùwèn", "Cố vấn", "Cố vấn, người tư vấn cao cấp", "Con người / People"],
    ["广阔", "廣闊", "guǎngkuò", "Quảng khoát", "Rộng lớn, bao la quảng khoát", "Tính từ / Adjectives"],
    ["规划", "規劃", "guīhuà", "Quy hoạch", "Quy hoạch, sơ đồ kế hoạch dài", "Danh từ / Nouns"],
    ["规矩", "規矩", "guīju", "Quy củ", "Quy củ, phép tắc, khuôn phép", "Danh từ / Nouns"],
    ["规律", "規律", "guīlǜ", "Quy luật", "Quy luật thiên nhiên/đời sống", "Danh từ / Nouns"],
    ["规模", "規模", "guīmó", "Quy mô", "Quy mô, tầm cỡ, diện tích", "Danh từ / Nouns"],
    ["规则", "規則", "guīzé", "Quy tắc", "Quy tắc, luật lệ trò chơi", "Danh từ / Nouns"],
    ["柜台", "櫃台", "guìtái", "Quỹ đài", "Quầy thu ngân, quầy phục vụ", "Đồ dùng / Items"],
    ["国防", "國防", "guófáng", "Quốc phòng", "Quốc phòng, bảo vệ biên cương", "Danh từ / Nouns"],
    ["豪华", "豪華", "háohuá", "Hào hoa", "Hào hoa, sang trọng, xa hoa", "Tính từ / Adjectives"],
    ["合理", "合理", "hélǐ", "Hợp lý", "Hợp lý, hợp logic lẽ phải", "Tính từ / Adjectives"],
    ["合作", "合作", "hézuò", "Hợp tác", "Hợp tác kinh doanh, chung sức", "Hành động / Actions"],
    ["核心", "核心", "héxīn", "Hạch tâm", "Trọng tâm, cốt lõi, hạt nhân", "Danh từ / Nouns"],
    ["恨", "恨", "hèn", "Hận", "Hận thù, căm ghét, hối tiếc", "Cảm xúc / Emotions"],
    ["横", "橫", "héng", "Hoành", "Nằm ngang, trục hoành", "Vị trí / Position"],
    ["后果", "後果", "hòuguǒ", "Hậu quả", "Hậu quả nghiêm trọng, kết cục", "Danh từ / Nouns"],
    ["呼吸", "呼吸", "hūxī", "Hô hấp", "Hô hấp, hít thở", "Hành động / Actions"],
    ["忽然", "忽然", "hūrán", "Hốt nhiên", "Đột nhiên, hốt nhiên", "Trạng từ / Adverbs"],
    ["忽视", "忽視", "hūshì", "Hốt thị", "Lơ là, phớt lờ, coi nhẹ", "Hành động / Actions"],
    ["胡说", "胡說", "húshuō", "Hồ thuyết", "Nói bậy, nói nhảm hồ đồ", "Hành động / Actions"],
    ["胡同", "胡同", "hútòng", "Hồ đồng", "Ngõ nhỏ cổ kính ở Bắc Kinh", "Địa điểm / Places"],
    ["华裔", "華裔", "huáyì", "Hoa duệ", "Người nước ngoài gốc Hoa", "Con người / People"],
    ["摆桌子", "擺桌子", "bǎi zhuōzi", "Bải trác tử", "Bày biện bàn ghế", "Hành động / Actions"],
    ["把握机会", "把握機會", "bǎwò jīhuì", "Bả ác cơ hội", "Nắm chắc cơ hội", "Hành động / Actions"],
    ["学校班主任", "學校班主任", "xuéxiào bānzhǔrèn", "Học hiệu ban chủ nhiệm", "Giáo viên chủ nhiệm trường", "Con người / People"],
    ["办理手续", "辦理手續", "bànlǐ shǒuxù", "Biện lý thủ tục", "Làm thủ tục hành chính", "Hành động / Actions"],
    ["傍晚时间", "傍晚時間", "bàngwǎn shíjiān", "Bạng vãn thời gian", "Thời điểm hoàng hôn/chiều tối", "Thời gian / Time"],
    ["热包子", "熱包子", "rè bāozi", "Nhiệt bao tử", "Bánh bao nóng", "Đồ ăn uống / Food & Drinks"],
    ["小宝贝", "小寶貝", "xiǎo bǎobèi", "Tiểu bảo bối", "Bé cưng, bảo bối nhỏ", "Con người / People"],
    ["宝贵经验", "寶貴經驗", "bǎoguì jīngyàn", "Bảo quý kinh nghiệm", "Kinh nghiệm quý báu", "Danh từ / Nouns"],
    ["保持联络", "保持聯絡", "bǎochí liánluò", "Bảo trì liên lạc", "Giữ liên lạc với nhau", "Hành động / Actions"],
    ["保存文件", "保存文件", "bǎocún wénjiàn", "Bảo tồn văn kiện", "Lưu trữ tập tin/tài liệu", "Hành động / Actions"],
    ["保留意见", "保留意見", "bǎoliú yìjiàn", "Bảo lưu ý kiến", "Giữ lại quan điểm cá nhân", "Hành động / Actions"],
    ["买保险", "買保險", "mǎi bǎoxiǎn", "Mãi bảo hiểm", "Mua bảo hiểm", "Hành động / Actions"],
    ["写报告", "寫報告", "xiě bàogào", "Tả báo cáo", "Viết bản báo cáo", "Học tập / Study"],
    ["态度悲观", "態度悲觀", "tàidu bēiguān", "Thái độ bi quan", "Thái độ bi quan buồn nản", "Cảm xúc / Emotions"],
    ["家庭背景", "家庭背景", "jiātíng bèijǐng", "Gia đình bối cảnh", "Hoàn cảnh gia đình", "Danh từ / Nouns"],
    ["盖被子", "蓋被子", "gài bèizi", "Cái bị tử", "Đắp chăn/mền", "Hành động / Actions"],
    ["大学本科", "大學本科", "dàxué běnkē", "Đại học bản khoa", "Hệ đại học chính quy", "Danh từ / Nouns"],
    ["有本领", "有本領", "yǒu běnlǐng", "Hữu bản lĩnh", "Có bản lĩnh, tài năng giỏi", "Danh từ / Nouns"],
    ["事物本质", "事物本質", "shìwù běnzhì", "Sự vật bản chất", "Bản chất của sự vật", "Danh từ / Nouns"],
    ["男女比例", "男女比例", "nán nǚ bǐlì", "Nam nữ tỷ lệ", "Tỷ lệ nam nữ", "Danh từ / Nouns"],
    ["彼此相爱", "彼此相愛", "bǐcǐ xiāng'ài", "Bỉ thử tương ái", "Yêu thương lẫn nhau", "Cảm xúc / Emotions"],
    ["必然结果", "必然結果", "bìrán jiéguǒ", "Tất nhiên kết quả", "Kết quả tất yếu/nhất định", "Danh từ / Nouns"],
    ["必要条件", "必要條件", "bìyào tiáojiàn", "Tất yếu điều kiện", "Điều kiện cần thiết/thiết yếu", "Danh từ / Nouns"],
    ["毕竟年轻", "畢竟年輕", "bìjìng niánqīng", "Tất cánh niên khinh", "Dù sao thì vẫn còn trẻ", "Trạng từ / Adverbs"],
    ["避免冲突", "避免衝突", "bìmiǎn chōngtū", "Tị miễn xung đột", "Tránh xung đột va chạm", "Hành động / Actions"],
    ["报纸编辑", "報紙編輯", "bàozhǐ biānjí", "Báo chỉ biên tập", "Biên tập viên tòa soạn báo", "Con người / People"],
    ["放鞭炮", "放鞭炮", "fàng biānpào", "Phóng tiên pháo", "Đốt pháo hoa/pháo nổ", "Hành động / Actions"],
    ["便走便说", "便走便說", "biàn zǒu biàn shuō", "Tiện tẩu tiện thuyết", "Vừa đi vừa nói chuyện", "Hành động / Actions"],
    ["辩论赛", "辯論賽", "biànlùnsài", "Biện luận tái", "Trận đấu tranh luận", "Giải trí / Entertainment"],
    ["写标点", "寫標點", "xiě biāodiǎn", "Tả tiêu điểm", "Viết dấu câu chính xác", "Học tập / Study"]
  ],
  6: [
    ["不可思议", "不可思議", "bùkě sīyì", "Bất khả tư nghị", "Không thể tin nổi, kỳ diệu", "Tính từ / Adjectives"],
    ["名副其实", "名副其實", "míng fù qí shí", "Danh phó kỳ thực", "Xứng danh thực tế, đúng danh", "Tính từ / Adjectives"],
    ["全力以赴", "全力以赴", "quán lì yǐ fù", "Toàn lực dĩ phó", "Dốc hết sức mình làm việc", "Hành động / Actions"],
    ["无微不至", "無微不至", "wú wēi bú zhì", "Vô vi bất chí", "Chu đáo tỉ mỉ từng tí một", "Tính từ / Adjectives"],
    ["理所当然", "理所當然", "lǐ suǒ dāng rán", "Lý sở đương nhiên", "Dĩ nhiên, lẽ đương nhiên", "Tính từ / Adjectives"],
    ["相辅相成", "相輔相成", "xiāng fǔ xiāng chéng", "Tương phụ tương thành", "Hỗ trợ và bổ sung cho nhau", "Tính từ / Adjectives"],
    ["精益求精", "精益求精", "jīng yì qiú jīng", "Tinh ích cầu tinh", "Ngày càng hoàn thiện, tỉ mỉ", "Tính từ / Adjectives"],
    ["塞翁失马", "塞翁失馬", "sài wēng shī mǎ", "Tái ông thất mã", "Trong cái rủi có cái may", "Tính từ / Adjectives"],
    ["产权", "產權", "chǎnquán", "Sản quyền", "Quyền sở hữu tài sản", "Danh từ / Nouns"],
    ["常识", "常識", "chángshí", "Thường thức", "Kiến thức phổ thông, thường thức", "Danh từ / Nouns"],
    ["朝代", "朝代", "cháodài", "Triều đại", "Triều đại lịch sử hoàng đế", "Danh từ / Nouns"],
    ["潮流", "潮流", "cháoliú", "Trào lưu", "Xu hướng thời đại, trào lưu", "Danh từ / Nouns"],
    ["成 kiến", "成見", "chéngjiàn", "Thành kiến", "Thành kiến, định kiến sẵn có", "Danh từ / Nouns"],
    ["阐述", "闡述", "chǎnshù", "Thiền thuật", "Trình bày rõ ràng chi tiết", "Hành động / Actions"],
    ["倡导", "倡導", "chàngdǎo", "Xướng đạo", "Khởi xướng, kêu gọi ủng hộ", "Hành động / Actions"],
    ["撤销", "撤銷", "chèxiāo", "Triệt tiêu", "Hủy bỏ, thu hồi, bãi bỏ", "Hành động / Actions"],
    ["撑", "撐", "chēng", "Sanh", "Chống đỡ, no căng cả bụng", "Hành động / Actions"],
    ["澄清", "澄清", "chéngqīng", "Trừng thanh", "Lọc trong nước, làm rõ thực hư", "Hành động / Actions"],
    ["呈现", "呈現", "chéngxiàn", "Trình hiện", "Hiện ra trước mắt, hiển lộ", "Hành động / Actions"],
    ["崇拜", "崇拜", "chóngbài", "Sùng bái", "Sùng bái, tôn thờ, ngưỡng mộ", "Cảm xúc / Emotions"],
    ["重叠", "重疊", "chóngdié", "Trùng điệp", "Chồng chất lên nhau, trùng lặp", "Trạng thái / States"],
    ["筹备", "籌備", "chóubèi", "Trù bị", "Chuẩn bị, trù bị cho đại hội", "Hành động / Actions"],
    ["出错", "出錯", "chūcuò", "Xuất thác", "Gặp lỗi sai, làm hỏng việc", "Trạng thái / States"],
    ["答辩", "答辯", "dábiàn", "Đáp biện", "Bảo vệ luận văn, biện luận lại", "Hành động / Actions"],
    ["奢侈", "奢侈", "shēchǐ", "Xa xỉ", "Xa xỉ, hoang phí tiền của", "Tính từ / Adjectives"],
    ["陈旧", "陳舊", "chénjiù", "Trần cựu", "Cũ kỹ, lỗi thời, trần cựu", "Tính từ / Adjectives"],
    ["持久", "持久", "chíjiǔ", "Trì cửu", "Bền bỉ, lâu dài, duy trì lâu", "Tính từ / Adjectives"],
    ["充沛", "充沛", "chōngpèi", "Sung phái", "Dồi dào sức sống, sung mãn", "Tính từ / Adjectives"],
    ["充足", "充足", "chōngzú", "Sung túc", "Đầy đủ sung túc, dư dả", "Tính từ / Adjectives"],
    ["丑恶", "醜惡", "chǒu'è", "Xú ác", "Xấu xa đê tiện, xấu xí ghê tởm", "Tính từ / Adjectives"],
    ["粗鲁", "粗魯", "cūlǔ", "Thô lỗ", "Thô lỗ cộc cằn, thô bạo", "Tính từ / Adjectives"],
    ["繁华", "繁華", "fánhuá", "Phồn hoa", "Sầm uất, phồn hoa đô hội", "Tính từ / Adjectives"],
    ["高超", "高超", "gāochāo", "Cao siêu", "Cao siêu, tuyệt hảo, xuất sắc", "Tính từ / Adjectives"],
    ["宏伟", "宏偉", "hóngwěi", "Hoành vĩ", "Hoành tráng, vĩ đại, hùng vĩ", "Tính từ / Adjectives"],
    ["荒谬", "荒謬", "huāngmiù", "Hoang miếu", "Hoang đường, nhảm nhí hoang miếu", "Tính từ / Adjectives"],
    ["尖端", "尖端", "jiānduān", "Tiêm đoan", "Tiên tiến, đỉnh cao, công nghệ nhọn", "Tính từ / Adjectives"],
    ["辽阔", "遼闊", "liáokuò", "Liêu khoát", "Bao la, rộng lớn khôn cùng", "Tính từ / Adjectives"],
    ["博大精深", "博大精深", "bódà jīngshēn", "Bác đại tinh thâm", "Rộng lớn tinh sâu (văn hóa)", "Tính từ / Adjectives"],
    ["捕捞海 lóng", "捕撈海龍", "bǔlāo hǎilóng", "Bộ lao hải long", "Đánh bắt rồng biển", "Hành động / Actions"],
    ["哺乳动物", "哺乳動物", "bǔrǔ dòngwù", "Bộ nhũ động vật", "Động vật có vú/cho con bú", "Động vật / Animals"],
    ["财务管理", "財務管理", "cáiwù guǎnlǐ", "Tài vụ quản lý", "Quản lý tài chính doanh nghiệp", "Danh từ / Nouns"],
    ["裁员计划", "裁員計劃", "cáiyuán jìhuà", "Tài viên kế hoạch", "Kế hoạch cắt giảm nhân sự", "Danh từ / Nouns"],
    ["政府采购", "政府採購", "zhèngfǔ cǎigòu", "Chính phủ thải cấu", "Mua sắm công của chính phủ", "Hành động / Actions"],
    ["采集标本", "采集標本", "cǎijí biāoběn", "Thải tập tiêu bản", "Thu thập mẫu vật/tiêu bản", "Hành động / Actions"],
    ["军事参谋", "軍事參謀", "jūnshì cānmóu", "Quân sự tham mưu", "Tham mưu trưởng quân đội", "Con người / People"],
    ["残留毒素", "殘留毒素", "cánliú dúsù", "Tàn lưu độc tố", "Chất độc còn sót lại", "Danh từ / Nouns"],
    ["阳光灿烂", "陽光燦爛", "yángguāng cànlàn", "Dương quang sạn lạn", "Ánh nắng rực rỡ chói chang", "Thiên nhiên / Nature"],
    ["仓促决定", "倉促決定", "cāngcù juédìng", "Thương xúc quyết định", "Quyết định vội vã vội vàng", "Hành động / Actions"],
    ["粮食仓库", "糧食倉庫", "liángshi cāngkù", "Lương thực thương khố", "Kho chứa lương thực thóc gạo", "Địa điểm / Places"],
    ["一生操劳", "一生操勞", "yīshēng cāoláo", "Nhất sinh thao lao", "Cả đời vất vả lo toan", "Hành động / Actions"],
    ["操练军队", "操練軍隊", "cāoliàn jūnduì", "Thao luyện quân đội", "Thao luyện quân đội chính quy", "Hành động / Actions"],
    ["法律草案", "法律草案", "fǎlǜ cǎo'àn", "Pháp luật thảo án", "Dự thảo bộ luật pháp lý", "Danh từ / Nouns"],
    ["第一册书", "第一冊書", "dì-yī cè shū", "Đệ nhất sách thư", "Tập sách đầu tiên/quyển một", "Đồ dùng / Items"],
    ["人物侧面", "人物側面", "rénwù cèmiàn", "Nhân vật trắc diện", "Mặt bên khía cạnh của người", "Con người / People"],
    ["数学测验", "數學測驗", "shùxué cèyàn", "Số học trắc nghiệm", "Bài kiểm tra toán học", "Học tập / Study"],
    ["新词层出不穷", "新詞層出不窮", "xīncí céng chū bù qióng", "Tân từ tằng xuất bất cùng", "Từ mới xuất hiện không ngừng", "Tính từ / Adjectives"],
    ["墙上插座", "牆上插座", "qiáng shàng chāzuò", "Tường thượng sáp tọa", "Ổ cắm điện trên tường nhà", "Đồ dùng / Items"],
    ["查获毒品", "查獲毒品", "cháhuò dúpǐn", "Tra hoạch độc phẩm", "Tịch thu ma túy lậu trái phép", "Hành động / Actions"],
    ["查勘现场", "查勘現場", "chákān xiànchǎng", "Tra khám hiện trường", "Khảo sát khám nghiệm hiện trường", "Hành động / Actions"],
    ["差别很大", "差別很大", "chābié hěn dà", "Sai biệt hận đại", "Khác biệt rất to lớn", "Tính từ / Adjectives"],
    ["叉子吃肉", "叉子吃肉", "chāzi chī ròu", "Xoa tử ngật nhục", "Dùng nĩa ăn thịt", "Đồ dùng / Items"],
    ["刹车按钮", "剎車按鈕", "shàchē ànniǔ", "Sát xa án nữu", "Nút bấm phanh/thắng xe", "Đồ dùng / Items"],
    ["诧异神色", "詫異神色", "chàyì shénsè", "Sá dị thần sắc", "Thần sắc ngơ ngác ngạc nhiên", "Cảm xúc / Emotions"],
    ["柴火取暖", "柴火取暖", "cháihuǒ qǔnuǎn", "Sài hỏa thủ noãn", "Đốt củi sưởi ấm trong đông", "Thiên nhiên / Nature"],
    ["豺狼野兽", "豺狼野獸", "cháiláng yěshòu", "Sài lang dã thú", "Sài lang dã thú hoang dã", "Động vật / Animals"],
    ["掺假产品", "摻假產品", "chānjiǎ chǎnpǐn", "Sâm giả sản phẩm", "Sản phẩm bị làm giả/trộn lộn", "Danh từ / Nouns"],
    ["搀扶老人", "攙扶老人", "chānfú lǎorén", "Sâm phù lão nhân", "Nâng đỡ dắt cụ già qua đường", "Hành động / Actions"],
    ["婵娟月亮", "嬋娟月亮", "chánjuān yuèliang", "Thiền quyên nguyệt lượng", "Ánh trăng thiền quyên sáng đẹp", "Thiên nhiên / Nature"],
    ["禅宗文化", "禪宗文化", "chánzōng wénhuà", "Thiền tông văn hóa", "Văn hóa phật giáo Thiền Tông", "Danh từ / Nouns"],
    ["极其缠绵", "極其纏綿", "jíqí chánmián", "Cực kỳ triền miên", "Khăng khít triền miên quyến luyến", "Tính từ / Adjectives"],
    ["产业发展", "產業發展", "chǎnyè fāzhǎn", "Sản nghiệp phát triển", "Phát triển công nghiệp/sản nghiệp", "Danh từ / Nouns"],
    ["阐明观点", "闡明觀點", "chǎnmíng guāndiǎn", "Thiền minh quan điểm", "Làm sáng tỏ quan điểm cá nhân", "Hành động / Actions"],
    ["颤抖双手", "顫抖雙手", "chàndǒu shuāngshǒu", "Chấn đầu song thủ", "Run rẩy hai bàn tay gầy gò", "Hành động / Actions"],
    ["猖獗犯罪", "猖獗犯罪", "chāngjué fànzuì", "Xương quyết phạm tội", "Tội phạm hoành hành猖獗", "Trạng thái / States"],
    ["繁荣昌盛", "繁榮昌盛", "fánróng chāngshèng", "Phồn vinh xương thịnh", "Phồn vinh xương thịnh giàu mạnh", "Trạng thái / States"],
    ["歌声嘹亮", "歌聲嘹亮", "gēshēng liáoliàng", "Ca thanh liêu lượng", "Tiếng hát vang lừng lộng gió", "Giải trí / Entertainment"],
    ["尝尝味道", "嘗嘗味道", "chángcháng wèidào", "Thường thường vị đạo", "Nếm thử mùi vị thức ăn", "Hành động / Actions"],
    ["偿还债务", "償還債務", "chánghuán zhàiwù", "Thường hoàn trái vụ", "Hoàn trả các khoản nợ nần", "Hành động / Actions"],
    ["常年工作", "常年工作", "chángnián gōngzuò", "Thường niên công tác", "Làm việc quanh năm suốt tháng", "Thời gian / Time"],
    ["常务理事", "常務理事", "chángwù lǐshì", "Thường vụ lý sự", "Ủy viên thường trực lý sự hội", "Con người / People"],
    ["敞开大门", "敞開大門", "chǎngkāi dàmén", "Sưởng khai đại môn", "Mở toang cánh cửa lớn đón chào", "Hành động / Actions"],
    ["畅销书籍", "暢銷書籍", "chàngxiāo shūjí", "Sướng tiêu thư tịch", "Sách bán chạy nhất sướng tiêu", "Đồ dùng / Items"],
    ["倡议环保", "倡議環保", "chàngyì huánbǎo", "Xướng nghị hoàn bảo", "Đề xướng bảo vệ môi trường", "Hành động / Actions"],
    ["抄写课文", "抄寫課文", "chāoxiě kèwén", "Sao tả khóa văn", "Sao chép lại bài khóa học", "Học tập / Study"],
    ["超越自我", "超越自我", "chāoyuè zìwǒ", "Siêu việt tự ngã", "Vượt qua giới hạn chính mình", "Hành động / Actions"],
    ["钞票面额", "鈔票面額", "chāopiào miàn'é", "Sao phiếu diện ngạch", "Mệnh giá tờ tiền giấy sao phiếu", "Danh từ / Nouns"],
    ["朝气蓬勃", "朝氣蓬勃", "zhāoqì péngbó", "Triêu khí bồng bột", "Tràn đầy sức sống tuổi trẻ", "Tính từ / Adjectives"],
    ["嘲笑别人", "嘲笑別人", "cháoxiào biéren", "Trào tiếu biệt nhân", "Chế giễu mỉa mai người khác", "Hành động / Actions"],
    ["潮湿空气", "潮濕空氣", "cháoshī kōngqì", "Triều thấp không khí", "Không khí ẩm ướt ẩm thấp", "Thiên nhiên / Nature"],
    ["大车间", "大車間", "dà chējiān", "Đại xa gian", "Phân xưởng sản xuất lớn", "Địa điểm / Places"],
    ["彻底解决", "徹底解決", "chèdǐ jiějué", "Triệt để giải quyết", "Giải quyết triệt để dứt điểm", "Hành động / Actions"],
    ["沉淀资金", "沉澱資金", "chéndiàn zījīn", "Trầm điện tư kim", "Vốn tích tụ/lắng đọng lại", "Danh từ / Nouns"],
    ["陈列商品", "陳列商品", "chénliè shāngpǐn", "Trần liệt thương phẩm", "Trưng bày bày biện hàng hóa", "Hành động / Actions"],
    ["陈述事实", "陳述事實", "chénshù shìshí", "Trần thuật sự thật", "Trình bày kể lại sự thật", "Hành động / Actions"],
    ["沉思默想", "沉思默想", "chénsī mòxiǎng", "Trầm tư mặc tưởng", "Trầm tư suy nghĩ mặc tưởng", "Nhận thức / Cognitive"],
    ["沉重负担", "沉重負擔", "chénzhòng fùdān", "Trầm trọng phụ đảm", "Gánh nặng trầm trọng nặng nề", "Danh từ / Nouns"],
    ["称心如意", "稱心如意", "chènxīn rúyì", "Xứng tâm như ý", "Vừa lòng vừa ý như nguyện", "Cảm xúc / Emotions"],
    ["称号荣誉", "稱號榮譽", "chēnghào róngyù", "Xưng hiệu vinh dự", "Danh hiệu vinh dự cao quý", "Danh từ / Nouns"],
    ["乘法计算", "乘法計算", "chéngfǎ jìsuàn", "Thừa pháp kế toán", "Phép tính nhân toán học", "Học tập / Study"],
    ["盛水木桶", "盛水木桶", "chéngshuǐ mùtǒng", "Thịnh thủy mộc thống", "Thùng gỗ đựng đầy nước mát", "Đồ dùng / Items"]
  ]
};

// Target file path
const filepath = path.join("src", "data", "vocabulary.js");

// Read file
const fileContent = fs.readFileSync(filepath, "utf8");

// Parse existing writingData array (use dynamic import)
import("../src/data/vocabulary.js").then(vocab => {
  const existingWritingData = vocab.writingData;
  console.log(`Original vocabulary size: ${existingWritingData.length} words.`);

  // Group existing words by level
  const levelGroups = { 1: [], 2: [], 3: [], 4: [], 5: [], 6: [] };
  existingWritingData.forEach(word => {
    levelGroups[word.level].push(word);
  });

  for (let lvl = 1; lvl <= 6; lvl++) {
    console.log(`Level ${lvl} currently has ${levelGroups[lvl].length} words.`);
  }

  // Next assigned ID start
  let newIdCounter = 1201;
  const newWritingData = [];

  // Track all existing simplified words to prevent duplicates in each level
  const existingSimplified = new Set(existingWritingData.map(w => w.simplified));
  const existingTraditional = new Set(existingWritingData.map(w => w.traditional));

  for (let lvl = 1; lvl <= 6; lvl++) {
    const currentLvlWords = [...levelGroups[lvl]];
    const currentLvlSimplified = new Set(currentLvlWords.map(w => w.simplified));
    const currentLvlTraditional = new Set(currentLvlWords.map(w => w.traditional));

    const lvlCandidates = candidates[lvl] || [];
    let addedCount = 0;

    for (const cand of lvlCandidates) {
      if (currentLvlWords.length >= 300) {
        break; // already reached 300 words
      }

      const [simplified, traditional, pinyin, sinoViet, translation, category] = cand;

      // Duplicate checks: ensure NOT already in this level
      if (currentLvlSimplified.has(simplified) || currentLvlTraditional.has(traditional)) {
        console.log(`[DUPLICATE IGNORED] Level ${lvl}: ${simplified} (${traditional})`);
        continue;
      }

      // Add new word
      const newWord = {
        id: `w${newIdCounter++}`,
        level: lvl,
        simplified,
        traditional,
        pinyin,
        sinoViet,
        translation,
        category
      };

      currentLvlWords.push(newWord);
      currentLvlSimplified.add(simplified);
      currentLvlTraditional.add(traditional);
      addedCount++;
    }

    console.log(`Level ${lvl}: Added ${addedCount} words. Total words: ${currentLvlWords.length}`);
    if (currentLvlWords.length !== 300) {
      console.error(`[ERROR] Level ${lvl} has ${currentLvlWords.length} words instead of exactly 300!`);
    }

    newWritingData.push(...currentLvlWords);
  }

  console.log(`Total expanded vocabulary: ${newWritingData.length} words.`);

  // Formatting the writingData array beautifully in Javascript code representation
  let formattedData = "export const writingData = [\n";
  newWritingData.forEach(word => {
    let line = `  { id: "${word.id}", level: ${word.level}, simplified: "${word.simplified}", traditional: "${word.traditional}", pinyin: "${word.pinyin}", `;
    if (word.sinoViet) {
      line += `sinoViet: "${word.sinoViet}", `;
    }
    line += `translation: "${word.translation}", category: "${word.category}" },\n`;
    formattedData += line;
  });
  formattedData += "];";

  // Replace writingData array block in the original fileContent string
  const writingDataRegex = /export\s+const\s+writingData\s*=\s*\[[\s\S]*?\];/;
  if (!writingDataRegex.test(fileContent)) {
    console.error("Could not find 'export const writingData = [...];' block in vocabulary.js");
    process.exit(1);
  }

  const updatedFileContent = fileContent.replace(writingDataRegex, formattedData);

  // Write back to vocabulary.js
  fs.writeFileSync(filepath, updatedFileContent, "utf8");
  console.log("Successfully expanded vocabulary.js!");
  process.exit(0);
}).catch(err => {
  console.error(err);
  process.exit(1);
});
